config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :members
  resources :events
  match "/index" =>'aaacore#index', via: :get

  match "/shop" =>'aaacore#shop', via: :get

  match "/discussion" =>'aaacore#discussion', via: :get

  root 'aaacore#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates_presence_of :event_id, :details, :author
	belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates_presence_of :title, :date, :description
	validates_uniqueness_of :title, :scope => :date
	has_many :comments, :dependent => :destroy
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/aaacore_controller.rb
class AaacoreController < ApplicationController
  def index
  	@title = "home"
  end

  def shop
  	@title = "shop"
  end

  def discussion
  	@title = "discussion"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :authenticate_member!, :except => [:index, :show]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.where(event_id: params[:event_id])
    @event = Event.find(params[:event_id])
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(event_id: params[:event_id] )
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comments.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comments = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:event_id, :details, :author)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_member!, :except => [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @comments = Comment.where(event_id: params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :description)
    end
end

app/helpers/aaacore_helper.rb
module AaacoreHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# return a title on per page basis.
	def title
		base_title = "MyRoRJourney"
		if @title.nil?
			base_title
		else
			"#{base_title}|#{@title}"
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/aaacore/discussion.html.erb
<h1>Aaacore#discussion</h1>
<p>Find me in app/views/aaacore/discussion.html.erb</p>

app/views/aaacore/events.html.erb
<h1>Aaacore#events</h1>
<p>Find me in app/views/aaacore/events.html.erb</p>

app/views/aaacore/index.html.erb
<article>
	<section id="main">
		<h1>This section is about randomness</h1>
		<p>
			Well in the randomness section I thought about writing something not absolutelr random for first paragraph, but second would be too random.
		</p>
		<p>
			I can do not what this sense make conquerers AOE GTA movie shawshank anything xps laptop macbook WOW.
		</p>

	</section>
	<section id="sidebar">
		<h1>This section is not random</h1>
		<p>
			In this section I am going to write about nothing, and nothing's gonna be very interesting about nothing, so you better do nothing and go about reading nothing till nothing
		</p>
		<p>
			Well you might be disappointed cause you thought atleast this section is not gonna be random so you might just read something, if not interesting, but you read NOTHING, first you got to read something, the you can decide... HAHAHA...
		</p>

	</section>
</article>

app/views/aaacore/shop.html.erb
<h1>Aaacore#shop</h1>
<p>Find me in app/views/aaacore/shop.html.erb</p>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :event_id %>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments for <%= event.title %></h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Details</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% comments.each do |comment| %>
      <tr>
        <td><%= comment.event_id %></td>
        <td><%= comment.details %></td>
        <td><%= comment.author %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Comment', new_comment_path(event_id: event) %>
<br>
<button id="hide_comments">Hide Comments</button>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path(event_id: @comment.event_id) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments for <%= @event.title %></h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Details</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.event_id %></td>
        <td><%= comment.details %></td>
        <td><%= comment.author %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path(event_id: @comment.event_id) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @comments.event_id %>
</p>

<p>
  <strong>Details:</strong>
  <%= @comments.details %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comments.author %>
</p>

<%= link_to 'Edit', edit_comment_path(@comments) %> |
<%= link_to 'Back', events_path(event_id: @comments.event_id) %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <% if member_signed_in? %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
         <% end %>
         <% if member_signed_in? %>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
  <%= link_to 'New Comment', new_comment_path(event_id: @event) %>
  </p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'List Comments', comments_path(event_id: @event) %> |
<%= link_to 'Back', events_path %> 

<section id="comments">
	<%= render 'comments/index', comments: @comments, event: @event %>
</section>

<button id="show_comments">Show Comments</button>

app/views/layouts/_footer.html.erb
<footer>
	(C) <%= Time.now.year %> Ashtead All. Asso.
</footer>

app/views/layouts/_header.html.erb
<header id="page_header" role="banner">
	<nav id="utility">
		<% if member_signed_in? %>
		signed in as <%= current_member.email %>:
		<%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>
		<% else %>
			<%= link_to "Sign up", new_member_registration_path %> or
			<%= link_to "Sign in", new_member_session_path %>
		<% end %>
	</nav>
	<h1>Ashtead Allotments Association</h1>
	<h2>Healthy Eating</h2>
</header>

app/views/layouts/_navigation.html.erb
<nav id="main_nav" role="navigation">
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Events", events_path %></li>
		<li><%= link_to "Discussion", discussion_path %></li>
		<li><%= link_to "Shop", shop_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <title><%= title %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
	<%= render 'layouts/header' %>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= render 'layouts/navigation' %>
	</section>

	<%= yield %>
	<%= render 'layouts/footer' %>
</div>

</body>
</html>